# Generated by Django 2.1.11 on 2019-08-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoApp', '0002_auto_20190806_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='academic_training',
            field=models.TextField(blank=True, null=True),
        ),
    ]
